import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script"; // ✅ Import Next.js Script component
import "./globals.css";

// Load Google Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// App Metadata
export const metadata = {
  title: "Fitness Web App",
  description: "Generated by create next app",
};

// Root Layout
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ✅ Ionicons Scripts */}
        <Script
          strategy="afterInteractive"
          type="module"
          src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"
        />
        <Script
          strategy="afterInteractive"
          noModule={true}
          src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"
        />

        {/* Render the app */}
        {children}
      </body>
    </html>
  );
}
